package decorator

import (
	"fmt"
	"go/ast"
	"go/token"
	"path/filepath"
	"strings"

	"github.com/moorara/gelato/internal/service/compiler"
)

type mainDecorator struct {
	imports []ast.Spec
	decls   []ast.Decl
}

func (d *mainDecorator) Package(info *compiler.PackageInfo, pkg *ast.Package) bool {
	return isMainPkg(info.PackageName)
}

func (d *mainDecorator) FilePre(info *compiler.FileInfo, file *ast.File) bool {
	d.imports, d.decls = nil, nil
	return true
}

func (d *mainDecorator) FilePost(info *compiler.FileInfo, file *ast.File) error {
	if len(d.imports) == 0 && len(d.decls) == 0 {
		return nil
	}

	// Imports
	importDecl := &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: d.imports,
	}

	newFile := &ast.File{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{Slash: 1, Text: "// DO NOT EDIT"},
				{Slash: 16, Text: "// Code generated by Gelato"},
			},
		},
		Package: 45,
		Name: &ast.Ident{
			NamePos: 53,
			Name:    info.PackageName,
		},
		Decls: append([]ast.Decl{importDecl}, d.decls...),
	}

	filePath := filepath.Join(info.BaseDir, decoratedDir, info.RelativeDir, info.FileName)
	if err := compiler.WriteFile(filePath, info.FileSet, newFile); err != nil {
		return err
	}

	return nil
}

func (d *mainDecorator) Import(info *compiler.FileInfo, spec *ast.ImportSpec) {
	d.imports = append(d.imports, spec)

	// Import decorated packages
	if importPath := strings.Trim(spec.Path.Value, `"`); isDecoratablePkg(importPath) {
		var decoratedPkgName string
		if spec.Name != nil {
			decoratedPkgName = spec.Name.Name
		} else {
			decoratedPkgName = filepath.Base(importPath)
		}

		decoratedPkgPath := strings.Replace(
			importPath,
			info.ModuleName,
			filepath.Join(info.ModuleName, decoratedDir),
			1,
		)

		d.imports = append(d.imports, &ast.ImportSpec{
			Name: &ast.Ident{
				Name: getDecoratedPkgName(decoratedPkgName),
			},
			Path: &ast.BasicLit{
				Value: fmt.Sprintf("%q", decoratedPkgPath),
			},
		})
	}
}

func (d *mainDecorator) FuncDecl(info *compiler.FuncInfo, funcType *ast.FuncType, body *ast.BlockStmt) {

}
